### ISSUE TITLE
It would be great if...

### ISSUE THREAD

**Issue by MBeijer** [capehill/os4sdl#3]
this project could somehow be merged with https://github.com/AmigaPorts/libSDL12 which is for OS3.x and based on libSDL 1.2.15.

A joint repo for all Amiga based OS'es would be great and better in the long run. I've tried the libSDL12 repo and it works for MorphOS (some minor issues) and OS3.x. Haven't tried OS4, as I used this repo for that purpose.

Just a thought/suggestion for the future.

**Comment by capehill** [comment]
Well I don't have objections.. only the usual lack of time. If both repos are now at the 1.2.15 level, it might be doable.

**Comment by MBeijer** [comment]
I made a team and a post regarding this in the AmigaPorts organisation. :) 

the m68k libSDL12 is based on the 1.2.15 sources, but the static ones from the website, rather than the more up to date repo. 

I made a fork of the SDL-mirror repo here on github and merged in all your and adtools commits to its SDL-1.2 branch, which you can find here: https://github.com/AmigaPorts/sdl/tree/SDL-1.2

I also merged in all the SDL2 commits from the sdl2-amigaos4 repo to the master branch: https://github.com/AmigaPorts/sdl/tree/master

This way, it's easier to pull new commits/changes from the SDL-mirror repo as they now share a common base!

**Comment by MBeijer** [comment]
You can find the post here:
https://github.com/orgs/AmigaPorts/teams/sdl/discussions/1

**Comment by capehill** [comment]
That is impressive job and well thought! Might save lots of time in the future.

**Comment by MBeijer** [comment]
:)

**Comment by capehill** [comment]
Closing this ticket, I will continue with https://github.com/AmigaPorts/SDL/tree/SDL-1.2
